'use client'

import { motion } from 'framer-motion'
import Image from 'next/image'

interface Project {
  title: string
  event: string
  description: string[]
  image: string
  githubUrl?: string
}

const projects: Project[] = [
  {
    title: 'Surgical-Tray Optimizer (STOp)',
    event: 'NTU CAO x ST Engineering Hackathon 2024',
    description: [
      'Introduced an optimization model that efficiently configures the required surgical tray for cataract surgery, resulting in a cost reduction of $4 million annually.',
      'Conceived a solution to utilize predictive analytics for assessing the risk of adverse events during operations, reducing the possibility of complications during surgery by 50%.',
      'Secured first runner-up position among 11 participating teams from a wide variety of disciplines at NTU.',
    ],
    image: '/assets/NTU_CampCode_Hackathon_2024.png',
  },
  {
    title: 'Video-Captioning Filtering Pipeline',
    event: 'NTU EEE Machine Learning and Data Analytics (MLDA) - Deep Learning Week 2024 Hackathon',
    description: [
      'Designed a power-efficient Python-based filtering pipeline to select high-quality video-caption pairs, improving the quality of the text-to-video generative model by 12%.',
      'Deployed machine learning based evaluation metrics (PyTorch) that reduce carbon emissions generated by 50% during the model training process.',
      'Achieved second place out of over 50 participating teams from various educational institutions in Singapore.',
    ],
    image: '/assets/MLDA_DLW_2024.png',
    githubUrl: 'https://github.com/yongzane00/DOVER-CLIP-based-data-filtering-pipeline',
  },
  {
    title: 'ConnectEZ - AAC Device for Aphasia Patients',
    event: 'Medical Device Design and Biomedical Project Design & Management',
    description: [
      'Led a team of 8 individuals in the development of an affordable AAC device, resulting in enhanced communication capabilities for Aphasia patients and a positive impact on their mental well-being.',
      'Utilized Google Firebase Realtime Database to securely log sensor data, enabling personalized treatment solutions while prioritizing user privacy and data security.',
      'Provided technical guidance to the team in proficiently utilizing programming languages including C, C++, and Arduino IDE to develop an advanced algorithm for user fall detection.',
    ],
    image: '/assets/Connect_EZ.jpg',
    githubUrl: 'https://github.com/3molga/BG4102-ConnectEZ',
  },
]

function ProjectCard({ title, event, description, image, githubUrl }: Project) {
  return (
    <motion.div
      className="bg-vscode-sidebar border border-vscode-border rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 hover:-translate-y-2"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true }}
    >
      <div className="flex flex-col lg:flex-row">
        {/* Image Section */}
        <div className="relative w-full lg:w-80 h-64 lg:h-auto flex-shrink-0">
          <Image
            src={image}
            alt={title}
            fill
            className="object-cover"
          />
        </div>
        
        {/* Content Section */}
        <div className="p-8 flex-1 flex flex-col">
          <div className="flex-1">
            <h3 className="text-2xl font-bold mb-3 syntax-function">{title}</h3>
            <p className="text-sm italic syntax-comment mb-6 bg-vscode-panel px-3 py-1 rounded-lg inline-block">
              {event}
            </p>
            
            <div className="space-y-4 mb-8">
              {description.map((point, index) => (
                <p key={index} className="text-vscode-text leading-relaxed relative pl-6">
                  <span className="absolute left-0 syntax-success font-bold text-lg">▸</span>
                  {point}
                </p>
              ))}
            </div>
          </div>
          
          {githubUrl && (
            <div className="flex justify-start">
              <a
                href={githubUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-vscode-keyword hover:bg-vscode-function text-vscode-bg px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
              >
                <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 0C5.374 0 0 5.373 0 12 0 17.302 3.438 21.8 8.207 23.387c.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z"/>
                </svg>
                View GitHub Project
              </a>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  )
}

export default function Projects() {
  return (
    <section id="projects" className="py-20 bg-vscode-editor relative overflow-hidden">
      <div className="absolute left-20 top-32 text-9xl font-bold text-vscode-keyword/5 select-none">
        &lt;/&gt;
      </div>
      
      <div className="container mx-auto px-6">
        <h2 className="text-4xl font-bold mb-12 text-center">
          <span className="syntax-comment">// </span>
          <span className="syntax-keyword">Projects</span>
        </h2>
        
        <div className="space-y-8 max-w-7xl mx-auto">
          {projects.map((project, index) => (
            <ProjectCard key={index} {...project} />
          ))}
        </div>
      </div>
    </section>
  )
}